import { PiecePosition } from "./types";

const InitialBoard: PiecePosition[] = [
  {
    position: { rank: 1, file: "a" },
    piece: "ROOK",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "b" },
    piece: "KNIGHT",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "c" },
    piece: "BISHOP",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "d" },
    piece: "QUEEN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "e" },
    piece: "KING",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "f" },
    piece: "BISHOP",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "g" },
    piece: "KNIGHT",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 1, file: "h" },
    piece: "ROOK",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "a" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "b" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "c" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "d" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "e" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "f" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "g" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 2, file: "h" },
    piece: "PAWN",
    colour: "WHITE",
    moved: false,
  },
  {
    position: { rank: 8, file: "a" },
    piece: "ROOK",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "b" },
    piece: "KNIGHT",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "c" },
    piece: "BISHOP",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "d" },
    piece: "QUEEN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "e" },
    piece: "KING",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "f" },
    piece: "BISHOP",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "g" },
    piece: "KNIGHT",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 8, file: "h" },
    piece: "ROOK",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "a" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "b" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "c" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "d" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "e" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "f" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: { rank: 7, file: "g" },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
  {
    position: {
      rank: 7,
      file: "h",
    },
    piece: "PAWN",
    colour: "BLACK",
    moved: false,
  },
];

export default InitialBoard;
